---
title: "Single nuclei RNASeq from DLPFC"
subtitle: "figures"
author:  |
 | Katia de Paiva Lopes 
 | Ricardo A. Vialle
 | Shinya Tasaki 
 |
 | Rush Alzheimer’s Disease Center
 | Chicago, IL 60612
date: "`r Sys.Date()`"
output: 
 rmarkdown::html_document:
   theme: spacelab
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true  
---

```{r clean.variables, echo=FALSE}
#This command clean all variables. BE CAREFULL!!! 
rm(list = setdiff(ls(), lsf.str()))
```

```{r Helper Functions, echo = FALSE}
createDT <- function(DF, caption="", scrollY=500){
  data <- DT::datatable(DF, caption=caption,
    extensions =  'Buttons',
    options = list( dom = 'Bfrtip', 
                    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'), 
                    scrollY = scrollY, scrollX=T, scrollCollapse = T, paging = F,  
                      columnDefs = list(list(className = 'dt-center', targets = "_all"))
    )
  ) 
   return(data)
}
```

```{r load_packages, message=F, warning=F}
library(tidyverse)
library(ggplot2)
library(ggsci)

net_dir = "/pastel/projects/speakeasy_dlpfc/SpeakEasy_singlenuclei/2nd_pass/snakemake-sn/results/mic/"
expression_dir = "/pastel/projects/speakeasy_dlpfc/SpeakEasy_singlenuclei/2nd_pass/snakemake-sn/input/"

# BN folders 
data_prefix = "mic_m46"
bn_results_dir = "/pastel/projects/speakeasy_dlpfc/BN/sn_dlpfc_mic_res/mic_modules/mic_m46/"
BN_run_dir = "/pastel/resources/bayesian_networks/CINDERellA/"
BN_output_dir = paste0(bn_results_dir,data_prefix,"_res")
BN_run_data = paste0(bn_results_dir,data_prefix,"_exp.txt")
```

# Expression data 
```{r expr_input}
mod2plot = 46 # Module we want to plot

# Expression data for a single set:
exprData = read.table(paste0(expression_dir, "mic.txt"), header = T, stringsAsFactors = F, check.names = F)
expr_matx = as.data.frame(exprData) # Residuals of the expression
gene_modules = read.table(paste0(net_dir, "geneBycluster.txt"), header = T, stringsAsFactors = F) # clusters from SpeakEasy

# Select the expression values for the module of interest 
to_plot = gene_modules$ensembl[gene_modules$cluster_lv3 == mod2plot]
expr_matx_mod = expr_matx[to_plot, ]

# Save the input expression for the BN
# save(expr_matx_mod, file = paste0(bn_results_dir,data_prefix,"_dataExp.RData"))
# write_csv(as.data.frame(expr_matx_mod), file = BN_run_data, col_names = F)
```

```{r, eval=F}
# CINDERellA has two inputs: exp.txt and output_folder 
setwd(BN_run_dir)
cmd_matlab_call = paste0("matlab -nodisplay -nojvm -nosplash -nodesktop -r")
cmd_matlab_param = paste0("runt=1000; data='",BN_run_data,"'; out_dir='",BN_output_dir,"'; run('",BN_run_dir,"CINDERellA.m')")
cmd_matlab_run = paste0(cmd_matlab_call, " \"",cmd_matlab_param,"\"")
cat(cmd_matlab_run)
system(cmd_matlab_run)
```

```{r dir, eval=FALSE}
# Results are saved here:
print(BN_output_dir)
```

# Read results
## Edges filtered
```{r}
# BN_output_dir = paste0(bn_results_dir,data_prefix,"_res")
# BN_run_data = paste0(bn_results_dir,data_prefix,"_exp.txt")

# load(file = paste0(bn_results_dir,data_prefix,"_BN_input.RData")) # phenotype_match,gene_net_metadata,mod_eigengen
# load(file = paste0(bn_results_dir,data_prefix,"_dataExp.RData"))

edgefrq = read_tsv(paste0(BN_output_dir,"/edgefrq.txt"), col_names = c("A","B","freq"), show_col_types = F)

dataExp = expr_matx_mod
edges_df = na.omit(cbind(edgefrq, rownames(dataExp)[edgefrq$A], rownames(dataExp)[edgefrq$B]))
colnames(edges_df) = c("fromNode", "toNode", "weight", "fromAltName", "toAltName") # match names for Cytoscape input

edges_df$fromAltName = gsub("(.*)\\.(.*)","\\1",edges_df$fromAltName)
edges_df$toAltName = gsub("(.*)\\.(.*)","\\1",edges_df$toAltName)

edges_filtered = edges_df[abs(edges_df$weight)>0.4, ] # weight default = 0.33
rownames(edges_filtered) = NULL

createDT(edges_filtered %>% arrange(-weight))
```

## Nodes filtered 
```{r fig.width=8, fig.height=8}
nodes_table = data.frame(nodeName = 1:nrow(dataExp), altName = gsub("(.*)\\.(.*)","\\1",rownames(dataExp))) %>% distinct()
nodes_table$altName = gsub("(.*)\\.(.*)","\\1",nodes_table$altName)
rownames(nodes_table) = NULL
nodes_table = na.omit(unique(nodes_table)) %>% left_join(unique(gene_modules[,c("ensembl","gene_name")]), by = c("altName"="ensembl"))

nodes_filtered = nodes_table[nodes_table$altName %in% unique(c(edges_filtered$fromAltName,edges_filtered$toAltName)), ]
nodes_filtered = nodes_filtered[! duplicated(nodes_filtered$altName), ] 

createDT(nodes_filtered)
```

# BN plot 
```{r function_plot, echo = FALSE, message=FALSE, results='hide', warning=FALSE}
library(igraph)
library(ggraph)
library(graphlayouts)
library(ggforce)
library(gtools)
library(tidyverse)
plot_geneBN <- function(edges_filtered, nodes_filtered, plot_title = "BN"){
  # Get the graph object
  g = igraph::graph_from_data_frame(d = edges_filtered[,c("fromAltName","toAltName","weight")], 
                            vertices = nodes_filtered[,c("altName","gene_name")], 
                            directed = T)
  V(g)$degree <- degree(g, mode = "in")
  ggraph(g, layout = "kk") +
    geom_edge_fan(
      aes(end_cap = circle(node2.degree + 3, "pt"),  
          #alpha = weight,                              # Edge transparency = freq
          edge_width = weight),                         # Edge width = 3 * freq
      edge_colour = "black",                           # Edge color
      arrow = arrow(angle = 15,                      
                    type = "closed",
                    ends = "last",
                    length = unit(0.15, "inches"))
      ) +
    geom_node_point(aes(size = I(degree)+5),              # Node size overlay
                    color = "#9467bd", # mic color  
                    show.legend = F) +
    shadowtext::geom_shadowtext(aes(x, y, label = gene_name), 
                                color = "black", 
                                size = 3.5, 
                                bg.colour = "white") +
    scale_edge_color_continuous(low = "grey66", high = "black") +
    scale_edge_width(range = c(0.1, 1)) +
    theme_graph() + 
    theme(legend.position = "right") + labs(title = plot_title)
}
```

```{r plot, warning=FALSE, fig.width=10, fig.height=8}
# Cairo::CairoPDF(file = "/pastel/Github_scripts/SpeakEasy_dlpfc/figures4paper/v3_may2024/bn_mic_m46.pdf", width = 10, height = 8) 
plot_geneBN(edges_filtered = edges_filtered,
          nodes_filtered = nodes_filtered)
# dev.off()
```

# Session 
```{r}
sessionInfo()
```

